export enum AppActions{
    SET_LANGUAGE = "SET_LANGUAGE",
    SET_CURRENCY = "SET_CURRENCY",
    SET_BLURRED = "SET_BLURRED",
    SET_UNBLURRED = "SET_UNBLURRED",
    SET_LOGGEDIN = "SET_LOGGEDIN",
    SET_LOGGEDOUT = "SET_LOGGEDOUT",
    OPEN_SIDEBAR = "OPEN_SIDEBAR",
    CLOSE_SIDEBAR = "CLOSE_SIDEBAR",
    OPEN_QUICKVIEW = "OPEN_QUICKVIEW",
    CLOSE_QUICKVIEW = "CLOSE_QUICKVIEW",
    SET_QUICKVIEW_HANDLE = "SET_QUICKVIEW_HANDLE",
}