export enum AppActions{
    SET_LANGUAGE = "SET_LANGUAGE",
    SET_CURRENCY = "SET_CURRENCY",
    SET_BLURRED = "SET_BLURRED",
    SET_UNBLURRED = "SET_UNBLURRED",
    SET_LOGGEDIN = "SET_LOGGEDIN",
    SET_LOGGEDOUT = "SET_LOGGEDOUT",
}