export enum CartActions {
    CREATE_CART = "CREATE_CART",
    ADD_TO_CART = "ADD_TO_CART",
    OPEN_CART = "OPEN_CART",
    CLOSE_CART = "CLOSE_CART",
    UPDATE_TOTAL_QUANTITY = "UPDATE_TOTAL_QUANTITY",
    UPDATE_OUT_OF_STOCK = "UPDATE_OUT_OF_STOCK",
}